// ==UserScript==
// @name         ChatGPT CSP DevScrapeWide
// @namespace    https://chatgpt.com/
// @version      0.1.0
// @description  Dev-only ChatGPT scrape and check controls for selector validation.
// @match        https://chatgpt.com/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

// Generated by tests/tampermonkey-dev-scrape/build-userscript.mjs

(function () {
  'use strict';

  const DevScrapeWide = (() => {
  const TM_STORAGE_PREFIX = 'tmDevScrapeWide:';
  const readTmStorageValue = (key) => {
    try {
      const raw = localStorage.getItem(TM_STORAGE_PREFIX + key);
      return raw == null ? null : JSON.parse(raw);
    } catch {
      return null;
    }
  };
  const writeTmStorageValue = (key, value) => {
    localStorage.setItem(TM_STORAGE_PREFIX + key, JSON.stringify(value));
  };
  const chrome = {
    storage: {
      local: {
        async get(keys) {
          if (typeof keys === 'string') return { [keys]: readTmStorageValue(keys) };
          if (Array.isArray(keys)) {
            return Object.fromEntries(keys.map((key) => [key, readTmStorageValue(key)]));
          }
          if (keys && typeof keys === 'object') {
            return Object.fromEntries(
              Object.entries(keys).map(([key, fallback]) => [
                key,
                readTmStorageValue(key) ?? fallback,
              ]),
            );
          }
          return {};
        },
        async set(items) {
          Object.entries(items || {}).forEach(([key, value]) => {
            writeTmStorageValue(key, value);
          });
        },
        async remove(keys) {
          const list = Array.isArray(keys) ? keys : [keys];
          list.forEach((key) => {
            localStorage.removeItem(TM_STORAGE_PREFIX + key);
          });
        },
      },
    },
    runtime: {
      getURL(relativePath) {
        return String(relativePath || '');
      },
    },
  };

  const BUILD_SOURCE_PRESENCE_BY_IDENTIFIER = {
    "data-testid=close-sidebar-button": true,
    "aria-controls=stage-slideover-sidebar": true,
    "id=page-header": true,
    "id=thread-bottom": true,
    "data-testid=composer-plus-btn": true,
    "data-testid=copy-turn-action-button": true,
    "data-testid=model-switcher-dropdown-button": true,
    "data-radix-menu-content": true,
    "data-testid=voice-play-turn-action-button": true,
    "svg-token=#03583c": true,
    "svg-token=#ec66f0": true,
    "name=contextual-retry-dropdown-input": true,
    "svg-token=#9254a2": true
  };

  const DEV_SCRAPE_WIDE_FIXTURE_URL =
    'https://chatgpt.com/share/69ea4c43-c770-83ea-8e47-8f23a993ec4a';
  const DEV_SCRAPE_WIDE_REPORT_PATH = 'dev-scrape/report.html';
  const DEV_SCRAPE_WIDE_LAST_REPORT_KEY = 'devScrapeWideLastReport';
  const DEV_SCRAPE_WIDE_LAST_FOLDER_KEY = 'devScrapeWideLastFolder';
  const DEV_SCRAPE_WIDE_CAPTURE_ROOT_REQUIRED_ERROR =
    'No capture directory is configured yet.';

  const HANDLE_DB_NAME = 'csp-dev-scrape';
  const HANDLE_STORE_NAME = 'handles';
  const HANDLE_KEY = 'inspectorCapturesRootHandle';
  const CAPTURE_ROOT_DIR_NAME = 'inspector-captures';
  const RUN_FOLDER_SUFFIX = 'devscrapewide_share-69ea4c43';
  const RUN_MANIFEST_NAME = 'run-manifest.json';
  const DEFERRED_FILENAME = '1c_TopbarToBottomEnabled_ThreadBottom.txt';
  const CONTENT_SOURCE_PATH = 'content.js';
  const TURN_SELECTOR =
    'section[data-testid^="conversation-turn-"], article[data-testid^="conversation-turn-"], article[data-turn]';
  const OPEN_MENU_SELECTOR = '[data-radix-menu-content][data-state="open"][role="menu"]';

  const DUMP_REGISTRY = Object.freeze([
    {
      filename: '1a_SideBarCollapsed_body.txt',
      stateId: 'sidebar-collapsed-body',
      label: 'Sidebar collapsed body',
      steps: [{ type: 'set-sidebar-state', state: 'collapsed', label: 'collapse sidebar' }],
      capture: { type: 'body' },
    },
    {
      filename: '1b_SidebarExpaneded_body.txt',
      stateId: 'sidebar-expanded-body',
      label: 'Sidebar expanded body',
      steps: [{ type: 'set-sidebar-state', state: 'expanded', label: 'expand sidebar' }],
      capture: { type: 'body' },
    },
    {
      filename: '1d_TopbarToBottomDisabled_ThreadBottom.txt',
      stateId: 'topbar-bottom-disabled-thread-bottom',
      label: 'Thread bottom area',
      steps: [],
      capture: { type: 'thread-bottom' },
    },
    {
      filename: '1e_TopbarToBottomDisabled_HeaderArea.txt',
      stateId: 'topbar-bottom-disabled-header-area',
      label: 'Header area',
      steps: [],
      capture: { type: 'header-area' },
    },
    {
      filename: '1f_UserTurnWithButtonsExposedOnHover.txt',
      stateId: 'user-turn-buttons-exposed',
      label: 'User turn with buttons exposed',
      steps: [{ type: 'focus-turn', turnRef: 'user-first', label: 'hover first user turn' }],
      capture: { type: 'current-turn' },
    },
    {
      filename: '1g_AgentTurnWithButtons_MultipleThreads_2of2_DidntSearchWeb.txt',
      stateId: 'assistant-turn-non-web-buttons-exposed',
      label: 'Assistant turn without web search',
      steps: [
        {
          type: 'focus-turn',
          turnRef: 'assistant-first-no-web',
          label: 'hover first non-web assistant turn',
        },
      ],
      capture: { type: 'current-turn' },
    },
    {
      filename: '1h_AgentTurnWithButtons_SingleThread_SearchedTheWeb.txt',
      stateId: 'assistant-turn-web-buttons-exposed',
      label: 'Assistant turn with web search',
      steps: [
        {
          type: 'focus-turn',
          turnRef: 'assistant-first-web',
          label: 'hover first web assistant turn',
        },
      ],
      capture: { type: 'current-turn' },
    },
    {
      filename: '2a_AgentOrUserTurn_SubmenuMoreActions3Dots_ReadAloudBranchButtons.txt',
      stateId: 'assistant-menu-read-aloud-branch',
      label: 'Assistant message menu with Read Aloud and Branch',
      steps: [
        {
          type: 'focus-turn',
          turnRef: 'assistant-first-no-web',
          label: 'hover first non-web assistant turn',
        },
        { type: 'open-turn-menu', label: 'open assistant message actions menu' },
      ],
      capture: { type: 'latest-open-menu' },
    },
    {
      filename:
        '2b_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu - Copy.txt',
      stateId: 'assistant-web-regenerate-menu-copy',
      label: 'Legacy alias of web regenerate menu',
      aliasOf: '2c_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu.txt',
    },
    {
      filename: '2c_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu.txt',
      stateId: 'assistant-web-regenerate-menu',
      label: 'Assistant web-search response menu',
      steps: [
        {
          type: 'focus-turn',
          turnRef: 'assistant-first-web',
          label: 'hover first web assistant turn',
        },
        { type: 'open-turn-menu', label: 'open web assistant message actions menu' },
      ],
      capture: { type: 'latest-open-menu' },
    },
    {
      filename: '2d_SubmenuForModelSwitcher_data-testid_model-switcher-dropdown-button.txt',
      stateId: 'model-switcher-menu',
      label: 'Model switcher menu',
      steps: [{ type: 'open-model-switcher-menu', label: 'open model switcher menu' }],
      capture: { type: 'latest-open-menu' },
    },
  ]);

  const DEFERRED_ARTIFACTS = Object.freeze([
    {
      filename: DEFERRED_FILENAME,
      stateId: 'topbar-bottom-enabled-thread-bottom',
      label: 'Deferred topbar-to-bottom thread-bottom capture',
      status: 'deferred',
    },
  ]);

  const CHECK_RULES = Object.freeze([
    {
      actionId: 'shortcutKeyToggleSidebar',
      identifier: 'data-testid=close-sidebar-button',
      sourcePattern: /close-sidebar-button/,
      searchNeedles: ['data-testid="close-sidebar-button"'],
      expectedFiles: ['1a_SideBarCollapsed_body.txt', '1b_SidebarExpaneded_body.txt'],
    },
    {
      actionId: 'shortcutKeyToggleSidebar',
      identifier: 'aria-controls=stage-slideover-sidebar',
      sourcePattern: /stage-slideover-sidebar/,
      searchNeedles: ['aria-controls="stage-slideover-sidebar"'],
      expectedFiles: ['1a_SideBarCollapsed_body.txt', '1b_SidebarExpaneded_body.txt'],
    },
    {
      actionId: 'shortcutKeyScrollToTop',
      identifier: 'id=page-header',
      sourcePattern: /#page-header/,
      searchNeedles: ['id="page-header"'],
      expectedFiles: ['1e_TopbarToBottomDisabled_HeaderArea.txt'],
    },
    {
      actionId: 'shortcutKeyClickNativeScrollToBottom',
      identifier: 'id=thread-bottom',
      sourcePattern: /#thread-bottom/,
      searchNeedles: ['id="thread-bottom"'],
      expectedFiles: ['1d_TopbarToBottomDisabled_ThreadBottom.txt'],
    },
    {
      actionId: 'shortcutKeyClickNativeScrollToBottom',
      identifier: 'data-testid=composer-plus-btn',
      sourcePattern: /composer-plus-btn/,
      searchNeedles: ['data-testid="composer-plus-btn"'],
      expectedFiles: [
        '1d_TopbarToBottomDisabled_ThreadBottom.txt',
        '1e_TopbarToBottomDisabled_HeaderArea.txt',
        '1a_SideBarCollapsed_body.txt',
        '1b_SidebarExpaneded_body.txt',
      ],
    },
    {
      actionId: 'shortcutKeyCopyLowest',
      identifier: 'data-testid=copy-turn-action-button',
      sourcePattern: /copy-turn-action-button/,
      searchNeedles: ['data-testid="copy-turn-action-button"'],
      expectedFiles: [
        '1f_UserTurnWithButtonsExposedOnHover.txt',
        '1g_AgentTurnWithButtons_MultipleThreads_2of2_DidntSearchWeb.txt',
        '1h_AgentTurnWithButtons_SingleThread_SearchedTheWeb.txt',
      ],
    },
    {
      actionId: 'shortcutKeyToggleModelSelector',
      identifier: 'data-testid=model-switcher-dropdown-button',
      sourcePattern: /model-switcher-dropdown-button/,
      searchNeedles: ['data-testid="model-switcher-dropdown-button"'],
      expectedFiles: [
        '1a_SideBarCollapsed_body.txt',
        '1b_SidebarExpaneded_body.txt',
        '1e_TopbarToBottomDisabled_HeaderArea.txt',
        '2d_SubmenuForModelSwitcher_data-testid_model-switcher-dropdown-button.txt',
      ],
    },
    {
      actionId: 'shortcutKeyToggleModelSelector',
      identifier: 'data-radix-menu-content',
      sourcePattern: /\[data-radix-menu-content]\[data-state="open"]\[role="menu"]/,
      searchNeedles: ['data-radix-menu-content'],
      expectedFiles: ['2d_SubmenuForModelSwitcher_data-testid_model-switcher-dropdown-button.txt'],
    },
    {
      actionId: 'shortcutKeyMoreDotsReadAloud',
      identifier: 'data-testid=voice-play-turn-action-button',
      sourcePattern: /voice-play-turn-action-button/,
      searchNeedles: ['data-testid="voice-play-turn-action-button"'],
      expectedFiles: ['2a_AgentOrUserTurn_SubmenuMoreActions3Dots_ReadAloudBranchButtons.txt'],
    },
    {
      actionId: 'shortcutKeyMoreDotsBranchInNewChat',
      identifier: 'svg-token=#03583c',
      sourcePattern: /\[shortcuts\.shortcutKeyMoreDotsBranchInNewChat][\s\S]+?#03583c/,
      searchNeedles: ['#03583c'],
      expectedFiles: ['2a_AgentOrUserTurn_SubmenuMoreActions3Dots_ReadAloudBranchButtons.txt'],
    },
    {
      actionId: 'shortcutKeyRegenerateTryAgain',
      identifier: 'svg-token=#ec66f0',
      sourcePattern: /\[shortcuts\.shortcutKeyRegenerateTryAgain][\s\S]+?#ec66f0/,
      searchNeedles: ['#ec66f0'],
      expectedFiles: [
        '2b_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu - Copy.txt',
        '2c_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu.txt',
      ],
    },
    {
      actionId: 'shortcutKeyRegenerateAskToChangeResponse',
      identifier: 'name=contextual-retry-dropdown-input',
      sourcePattern: /contextual-retry-dropdown-input/,
      searchNeedles: ['name="contextual-retry-dropdown-input"'],
      expectedFiles: [
        '2b_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu - Copy.txt',
        '2c_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu.txt',
      ],
    },
    {
      actionId: 'shortcutKeyRegenerateWithDifferentModel',
      identifier: 'svg-token=#9254a2',
      sourcePattern: /\[shortcuts\.shortcutKeyRegenerateWithDifferentModel][\s\S]+?#9254a2/,
      searchNeedles: ['#9254a2'],
      expectedFiles: [
        '2b_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu - Copy.txt',
        '2c_AgentOrUserTurn_SubmenuRegenerate_AfterWebSearchResponse_RegenerateSubmenu.txt',
      ],
    },
  ]);

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  function escapeHtmlText(value) {
    return String(value || '')
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');
  }

  function escapeHtmlAttribute(value) {
    return escapeHtmlText(value).replaceAll('"', '&quot;');
  }

  function isVisible(element) {
    if (!(element instanceof Element) || !element.isConnected) return false;
    const style = element.ownerDocument?.defaultView?.getComputedStyle?.(element);
    if (!style) return false;
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0')
      return false;
    const rect = element.getBoundingClientRect();
    return rect.width > 0 && rect.height > 0;
  }

  function smartClick(element, windowObj) {
    if (!(element instanceof Element)) return false;
    const init = { bubbles: true, cancelable: true, view: windowObj };
    const ctorList = [
      ['pointerdown', windowObj.PointerEvent || windowObj.MouseEvent],
      ['mousedown', windowObj.MouseEvent],
      ['pointerup', windowObj.PointerEvent || windowObj.MouseEvent],
      ['mouseup', windowObj.MouseEvent],
      ['click', windowObj.MouseEvent],
    ];
    ctorList.forEach(([type, Ctor]) => {
      try {
        element.dispatchEvent(new Ctor(type, init));
      } catch {}
    });
    try {
      element.click();
      return true;
    } catch {
      return false;
    }
  }

  function dispatchHover(element, windowObj) {
    if (!(element instanceof Element)) return false;
    const rect = element.getBoundingClientRect();
    const clientX = rect.left + Math.max(1, Math.min(rect.width - 1, rect.width / 2 || 1));
    const clientY = rect.top + Math.max(1, Math.min(rect.height - 1, rect.height / 2 || 1));
    const init = {
      bubbles: true,
      cancelable: true,
      clientX,
      clientY,
      view: windowObj,
    };
    const ctor = windowObj.PointerEvent || windowObj.MouseEvent;
    ['pointerover', 'mouseover', 'mouseenter', 'pointermove', 'mousemove'].forEach((type) => {
      try {
        element.dispatchEvent(new ctor(type, init));
      } catch {}
    });
    return true;
  }

  function describeError(error) {
    if (!error) return 'Unknown error';
    if (typeof error === 'string') return error;
    if (typeof error.message === 'string' && error.message) return error.message;
    return String(error);
  }

  function isAbortError(error) {
    return error?.name === 'AbortError';
  }

  async function waitForCondition(getter, { timeout = 2000, interval = 50 } = {}) {
    const startedAt = Date.now();
    while (Date.now() - startedAt < timeout) {
      const value = getter();
      if (value) return value;
      await sleep(interval);
    }
    return null;
  }

  function getTurnElements(documentObj) {
    return Array.from(documentObj.querySelectorAll(TURN_SELECTOR)).filter(
      (element) => element instanceof Element,
    );
  }

  function hasWebCitation(turn) {
    return !!turn?.querySelector?.('[data-testid="webpage-citation-pill"]');
  }

  function isAssistantTurn(turn) {
    return (
      turn?.getAttribute?.('data-turn') === 'assistant' ||
      !!turn?.querySelector?.('[data-message-author-role="assistant"]')
    );
  }

  function isUserTurn(turn) {
    return (
      turn?.getAttribute?.('data-turn') === 'user' ||
      !!turn?.querySelector?.('[data-message-author-role="user"]')
    );
  }

  function findTurnByRef(documentObj, turnRef) {
    const turns = getTurnElements(documentObj);
    if (turnRef === 'user-first') {
      return turns.find((turn) => isUserTurn(turn)) || null;
    }
    if (turnRef === 'assistant-first-no-web') {
      return turns.find((turn) => isAssistantTurn(turn) && !hasWebCitation(turn)) || null;
    }
    if (turnRef === 'assistant-first-web') {
      return turns.find((turn) => isAssistantTurn(turn) && hasWebCitation(turn)) || null;
    }
    return null;
  }

  function getOpenMenuWrappers(documentObj) {
    return Array.from(documentObj.querySelectorAll(OPEN_MENU_SELECTOR))
      .map((menu) => menu.closest('[data-radix-popper-content-wrapper]') || menu)
      .filter((element) => element instanceof Element && element.isConnected);
  }

  async function closeOpenMenus(documentObj, windowObj) {
    const dispatchEscape = () => {
      const target = documentObj.activeElement || documentObj.body || documentObj.documentElement;
      ['keydown', 'keyup'].forEach((type) => {
        try {
          target.dispatchEvent(
            new windowObj.KeyboardEvent(type, {
              key: 'Escape',
              code: 'Escape',
              bubbles: true,
              cancelable: true,
            }),
          );
        } catch {}
      });
    };
    for (let attempt = 0; attempt < 3; attempt += 1) {
      if (!getOpenMenuWrappers(documentObj).length) return;
      dispatchEscape();
      await sleep(100);
    }
  }

  function serializeNodePretty(node, depth = 0) {
    const indent = '  '.repeat(depth);
    if (node.nodeType === node.TEXT_NODE) {
      const text = String(node.textContent || '')
        .replaceAll('\r', '')
        .trim();
      return text ? `${indent}${escapeHtmlText(text)}` : '';
    }
    if (node.nodeType === node.COMMENT_NODE) {
      return `${indent}<!--${node.textContent || ''}-->`;
    }
    if (node.nodeType !== node.ELEMENT_NODE) return '';
    const tagName = node.tagName.toLowerCase();
    const attrs = Array.from(node.attributes)
      .map((attribute) => ` ${attribute.name}="${escapeHtmlAttribute(attribute.value)}"`)
      .join('');
    const children = Array.from(node.childNodes)
      .map((child) => serializeNodePretty(child, depth + 1))
      .filter(Boolean);
    if (!children.length) {
      return `${indent}<${tagName}${attrs}></${tagName}>`;
    }
    return `${indent}<${tagName}${attrs}>\n${children.join('\n')}\n${indent}</${tagName}>`;
  }

  function normalizeHtmlForDump(windowObj, html) {
    const documentObj = windowObj.document;
    const htmlDoc = documentObj.implementation.createHTMLDocument('csp-dev-scrape');
    const container = htmlDoc.createElement('div');
    container.innerHTML = String(html || '').trim();
    return Array.from(container.childNodes)
      .map((node) => serializeNodePretty(node, 0))
      .filter(Boolean)
      .join('\n');
  }

  function findThreadBottomElement(documentObj) {
    return (
      documentObj.getElementById('thread-bottom') ||
      documentObj.getElementById('thread-bottom-container') ||
      null
    );
  }

  function findHeaderAreaElement(documentObj) {
    const header = documentObj.getElementById('page-header');
    if (!header) return null;
    return header.closest('[data-scroll-root]') || header.parentElement || header;
  }

  function getTurnActionGroup(turn) {
    if (!(turn instanceof Element)) return null;
    const candidates = Array.from(
      turn.querySelectorAll(
        '[role="group"], [aria-label="Response actions"], [aria-label="Your message actions"]',
      ),
    ).filter(
      (element) =>
        element instanceof Element && isVisible(element) && element.querySelector('button'),
    );
    return candidates[0] || null;
  }

  function getTurnMenuTrigger(turn) {
    const group = getTurnActionGroup(turn);
    if (!(group instanceof Element)) return null;
    const buttons = Array.from(group.querySelectorAll('button')).filter((button) =>
      isVisible(button),
    );
    return (
      buttons.find((button) => button.getAttribute('aria-haspopup') === 'menu') ||
      buttons.find((button) => button.getAttribute('data-testid') !== 'copy-turn-action-button') ||
      null
    );
  }

  async function ensureSidebarState(documentObj, windowObj, state) {
    const closeButton = documentObj.querySelector('button[data-testid="close-sidebar-button"]');
    const openButton =
      documentObj.querySelector('button[data-testid="open-sidebar-button"]') ||
      documentObj.querySelector(
        '#stage-sidebar-tiny-bar button[aria-controls="stage-slideover-sidebar"]',
      );
    if (state === 'collapsed') {
      if (closeButton && isVisible(closeButton)) {
        smartClick(closeButton, windowObj);
        await sleep(250);
      }
      return;
    }
    if (state === 'expanded') {
      if (closeButton && isVisible(closeButton)) return;
      if (!openButton || !isVisible(openButton)) {
        throw new Error('Could not find a visible sidebar open control');
      }
      smartClick(openButton, windowObj);
      await sleep(300);
    }
  }

  async function focusTurn(documentObj, windowObj, turnRef, runtime) {
    const turn = findTurnByRef(documentObj, turnRef);
    if (!(turn instanceof Element)) {
      throw new Error(`Could not find turn for ${turnRef}`);
    }
    try {
      turn.scrollIntoView({ block: 'center', inline: 'nearest' });
    } catch {}
    dispatchHover(turn, windowObj);
    await sleep(120);
    runtime.currentTurn = turn;
    return turn;
  }

  async function openTurnMenu(documentObj, windowObj, runtime) {
    const turn = runtime.currentTurn;
    if (!(turn instanceof Element)) throw new Error('No current turn is selected');
    await closeOpenMenus(documentObj, windowObj);
    dispatchHover(turn, windowObj);
    await sleep(80);
    const trigger = getTurnMenuTrigger(turn);
    if (!(trigger instanceof Element)) {
      throw new Error('Could not find a visible turn menu trigger');
    }
    smartClick(trigger, windowObj);
    const menu = await waitForCondition(() => getOpenMenuWrappers(documentObj).slice(-1)[0] || null, {
      timeout: 2000,
      interval: 50,
    });
    if (!(menu instanceof Element)) {
      throw new Error('Turn menu did not open');
    }
    runtime.latestMenu = menu;
    return menu;
  }

  async function openModelSwitcherMenu(documentObj, windowObj, runtime) {
    await closeOpenMenus(documentObj, windowObj);
    const button = documentObj.querySelector('button[data-testid="model-switcher-dropdown-button"]');
    if (!(button instanceof Element) || !isVisible(button)) {
      throw new Error('Could not find a visible model switcher button');
    }
    smartClick(button, windowObj);
    const menu = await waitForCondition(
      () =>
        getOpenMenuWrappers(documentObj).find((candidate) =>
          candidate.querySelector?.('[data-testid^="model-switcher-"]'),
        ) || null,
      {
        timeout: 2000,
        interval: 50,
      },
    );
    if (!(menu instanceof Element)) {
      throw new Error('Model switcher menu did not open');
    }
    runtime.latestMenu = menu;
    return menu;
  }

  async function executeStep(documentObj, windowObj, runtime, step) {
    if (step.type === 'set-sidebar-state') {
      await ensureSidebarState(documentObj, windowObj, step.state);
      return;
    }
    if (step.type === 'focus-turn') {
      await focusTurn(documentObj, windowObj, step.turnRef, runtime);
      return;
    }
    if (step.type === 'open-turn-menu') {
      await openTurnMenu(documentObj, windowObj, runtime);
      return;
    }
    if (step.type === 'open-model-switcher-menu') {
      await openModelSwitcherMenu(documentObj, windowObj, runtime);
      return;
    }
    throw new Error(`Unsupported scrape step: ${step.type}`);
  }

  function captureArtifactHtml(documentObj, runtime, capture) {
    if (capture.type === 'body') {
      return documentObj.body?.outerHTML || '';
    }
    if (capture.type === 'thread-bottom') {
      return findThreadBottomElement(documentObj)?.outerHTML || '';
    }
    if (capture.type === 'header-area') {
      return findHeaderAreaElement(documentObj)?.outerHTML || '';
    }
    if (capture.type === 'current-turn') {
      return runtime.currentTurn?.outerHTML || '';
    }
    if (capture.type === 'latest-open-menu') {
      const menu = runtime.latestMenu || getOpenMenuWrappers(documentObj).slice(-1)[0] || null;
      return menu?.outerHTML || '';
    }
    return '';
  }

  function makeArtifactRecord(definition, override = {}) {
    return {
      filename: definition.filename,
      stateId: definition.stateId,
      label: definition.label,
      ...override,
    };
  }

  function getLocalTimestampParts(date) {
    const pad = (value) => String(value).padStart(2, '0');
    return {
      year: date.getFullYear(),
      month: pad(date.getMonth() + 1),
      day: pad(date.getDate()),
      hour: pad(date.getHours()),
      minute: pad(date.getMinutes()),
      second: pad(date.getSeconds()),
    };
  }

  function buildRunFolderName(date = new Date()) {
    const parts = getLocalTimestampParts(date);
    return `${parts.year}-${parts.month}-${parts.day}_${parts.hour}-${parts.minute}-${parts.second}_${RUN_FOLDER_SUFFIX}`;
  }

  async function getUniqueRunDirectoryHandle(rootHandle, preferredName) {
    let candidateName = preferredName;
    let suffix = 0;
    for (;;) {
      try {
        await rootHandle.getDirectoryHandle(candidateName);
        suffix += 1;
        candidateName = `${preferredName}_${String(suffix).padStart(2, '0')}`;
      } catch {
        return rootHandle.getDirectoryHandle(candidateName, { create: true });
      }
    }
  }

  async function openHandleDatabase() {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(HANDLE_DB_NAME, 1);
      request.onupgradeneeded = () => {
        if (!request.result.objectStoreNames.contains(HANDLE_STORE_NAME)) {
          request.result.createObjectStore(HANDLE_STORE_NAME);
        }
      };
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error || new Error('Could not open IndexedDB'));
    });
  }

  async function idbGet(key) {
    const db = await openHandleDatabase();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(HANDLE_STORE_NAME, 'readonly');
      const request = transaction.objectStore(HANDLE_STORE_NAME).get(key);
      request.onsuccess = () => resolve(request.result || null);
      request.onerror = () => reject(request.error || new Error('Could not read IndexedDB value'));
    });
  }

  async function idbSet(key, value) {
    const db = await openHandleDatabase();
    return new Promise((resolve, reject) => {
      const transaction = db.transaction(HANDLE_STORE_NAME, 'readwrite');
      const request = transaction.objectStore(HANDLE_STORE_NAME).put(value, key);
      request.onsuccess = () => resolve(value);
      request.onerror = () => reject(request.error || new Error('Could not write IndexedDB value'));
    });
  }

  async function getStoredLastRunFolderInfo() {
    const stored = await chrome.storage.local.get(DEV_SCRAPE_WIDE_LAST_FOLDER_KEY);
    const value = stored?.[DEV_SCRAPE_WIDE_LAST_FOLDER_KEY];
    if (!value || typeof value !== 'object') return null;
    const folderName = String(value.folderName || '').trim();
    if (!folderName) return null;
    return {
      folderName,
      completedAt: typeof value.completedAt === 'string' ? value.completedAt : null,
    };
  }

  async function setStoredLastRunFolderInfo({ folderName, completedAt = null }) {
    const normalizedFolderName = String(folderName || '').trim();
    if (!normalizedFolderName) return;
    await chrome.storage.local.set({
      [DEV_SCRAPE_WIDE_LAST_FOLDER_KEY]: {
        folderName: normalizedFolderName,
        completedAt: typeof completedAt === 'string' ? completedAt : null,
      },
    });
  }

  async function clearStoredLastRunFolderInfo() {
    await chrome.storage.local.remove(DEV_SCRAPE_WIDE_LAST_FOLDER_KEY);
  }

  async function ensureDirectoryPermission(handle, { interactive = false } = {}) {
    if (!handle || handle.kind !== 'directory') return null;
    const options = { mode: 'readwrite' };
    if ((await handle.queryPermission?.(options)) === 'granted') return handle;
    if (interactive && (await handle.requestPermission?.(options)) === 'granted') return handle;
    return null;
  }

  async function clearStoredCaptureRootHandle() {
    await idbSet(HANDLE_KEY, null);
    await clearStoredLastRunFolderInfo();
  }

  async function ensureCaptureRootHandle(
    windowObj,
    { interactive = false, forcePick = false } = {},
  ) {
    let handle = null;
    if (!forcePick) {
      handle = await ensureDirectoryPermission(await idbGet(HANDLE_KEY), { interactive });
    }
    if (!handle && interactive) {
      if (typeof windowObj?.showDirectoryPicker !== 'function') {
        throw new Error('Directory picker is unavailable in this extension page');
      }
      handle = await windowObj.showDirectoryPicker({ mode: 'readwrite' });
      handle = await ensureDirectoryPermission(handle, { interactive: true });
      if (!handle) {
        throw new Error('Write permission was not granted for the capture directory');
      }
      await idbSet(HANDLE_KEY, handle);
    }
    if (!handle) {
      throw new Error(
        `${DEV_SCRAPE_WIDE_CAPTURE_ROOT_REQUIRED_ERROR} Click Set Path first and choose the ${CAPTURE_ROOT_DIR_NAME} folder.`,
      );
    }
    return handle;
  }

  async function configureCaptureRootHandle(windowObj) {
    const handle = await ensureCaptureRootHandle(windowObj, { interactive: true, forcePick: true });
    await clearStoredLastRunFolderInfo();
    return handle;
  }

  function isCaptureRootRequiredError(error) {
    return String(error?.message || '').startsWith(DEV_SCRAPE_WIDE_CAPTURE_ROOT_REQUIRED_ERROR);
  }

  async function writeTextFile(directoryHandle, fileName, text) {
    const fileHandle = await directoryHandle.getFileHandle(fileName, { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(text);
    await writable.close();
  }

  async function readTextFile(directoryHandle, fileName) {
    const fileHandle = await directoryHandle.getFileHandle(fileName);
    const file = await fileHandle.getFile();
    return file.text();
  }

  async function listDirectoryEntries(directoryHandle) {
    const entries = [];
    for await (const [name, handle] of directoryHandle.entries()) {
      entries.push({ name, handle });
    }
    return entries;
  }

  function buildRunSortKey(date, suffix = 0) {
    if (!(date instanceof Date) || Number.isNaN(date.getTime())) return '';
    return `${String(date.getTime()).padStart(16, '0')}_${String(Math.max(0, suffix)).padStart(4, '0')}`;
  }

  function parseRunFolderSortKey(name) {
    const match =
      /^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})_devscrapewide_share-69ea4c43(?:([_-])(\d+))?$/.exec(
        String(name || ''),
      );
    if (!match) return '';
    return buildRunSortKey(
      new Date(
        Number(match[1]),
        Number(match[2]) - 1,
        Number(match[3]),
        Number(match[4]),
        Number(match[5]),
        Number(match[6]),
      ),
      Number.parseInt(match[8] || '0', 10),
    );
  }

  function parseManifestSortKey(manifest) {
    const stamp = manifest?.completedAt || manifest?.startedAt;
    if (!stamp) return '';
    return buildRunSortKey(new Date(stamp));
  }

  async function getNamedRunDirectoryHandle(rootHandle, folderName) {
    const normalizedFolderName = String(folderName || '').trim();
    if (!normalizedFolderName) return null;
    try {
      const handle = await rootHandle.getDirectoryHandle(normalizedFolderName);
      return { name: normalizedFolderName, handle };
    } catch {
      return null;
    }
  }

  async function getLatestRunDirectoryHandle(rootHandle) {
    const directories = await Promise.all(
      (await listDirectoryEntries(rootHandle))
        .filter((entry) => entry.handle?.kind === 'directory')
        .map(async (entry) => {
          const folderSortKey = parseRunFolderSortKey(entry.name);
          if (folderSortKey) return { ...entry, sortKey: folderSortKey };
          try {
            const manifestText = await readTextFile(entry.handle, RUN_MANIFEST_NAME);
            return {
              ...entry,
              sortKey: parseManifestSortKey(JSON.parse(manifestText)),
            };
          } catch {
            return null;
          }
        }),
    );
    const sortableDirectories = directories.filter((entry) => entry?.sortKey);
    sortableDirectories.sort((left, right) => left.sortKey.localeCompare(right.sortKey));
    return sortableDirectories[sortableDirectories.length - 1] || null;
  }

  async function getPreferredRunDirectoryHandle(rootHandle) {
    const storedFolderInfo = await getStoredLastRunFolderInfo();
    const storedRunDirectory = await getNamedRunDirectoryHandle(
      rootHandle,
      storedFolderInfo?.folderName,
    );
    if (storedRunDirectory) return storedRunDirectory;
    return getLatestRunDirectoryHandle(rootHandle);
  }

  async function storeLastRunAfterPersist(runDirectoryName, completedAt) {
    await setStoredLastRunFolderInfo({
      folderName: runDirectoryName,
      completedAt: completedAt || new Date().toISOString(),
    });
  }

  async function fetchPackagedText(relativePath) {
    const response = await fetch(chrome.runtime.getURL(relativePath), { cache: 'no-store' });
    if (!response.ok) {
      throw new Error(`Could not read packaged file: ${relativePath}`);
    }
    return response.text();
  }

  function getWideScrapePageInfo({ windowObj, documentObj }) {
    const turns = getTurnElements(documentObj);
    return {
      url: windowObj.location.href,
      title: documentObj.title || '',
      fixtureUrl: DEV_SCRAPE_WIDE_FIXTURE_URL,
      fixtureOk: windowObj.location.href === DEV_SCRAPE_WIDE_FIXTURE_URL,
      turnCount: turns.length,
      assistantTurnCount: turns.filter((turn) => isAssistantTurn(turn)).length,
      userTurnCount: turns.filter((turn) => isUserTurn(turn)).length,
      hasWebSearchTurn: turns.some((turn) => isAssistantTurn(turn) && hasWebCitation(turn)),
    };
  }

  async function runWideScrapeInPage({ windowObj, documentObj }) {
    const pageInfo = getWideScrapePageInfo({ windowObj, documentObj });
    if (!pageInfo.fixtureOk) {
      return {
        ok: false,
        error: `Active tab does not match the required fixture.\n\nExpected:\n${DEV_SCRAPE_WIDE_FIXTURE_URL}\n\nActual:\n${pageInfo.url || '(unknown)'}`,
        runKind: 'devscrapewide',
        fixtureUrl: DEV_SCRAPE_WIDE_FIXTURE_URL,
        pageInfo,
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        artifacts: [],
        capturedCount: 0,
        failedCount: 0,
        deferredCount: DEFERRED_ARTIFACTS.length,
      };
    }
    const startedAt = new Date().toISOString();
    const runtime = {
      currentTurn: null,
      latestMenu: null,
    };
    const artifacts = [];
    const capturedByFileName = new Map();

    for (const definition of DUMP_REGISTRY) {
      if (definition.aliasOf) continue;
      try {
        await closeOpenMenus(documentObj, windowObj);
        runtime.latestMenu = null;
        const steps = Array.isArray(definition.steps) ? definition.steps : [];
        if (steps.length > 5) {
          throw new Error(`Artifact ${definition.filename} exceeds the 5-step limit`);
        }
        for (const step of steps) {
          await executeStep(documentObj, windowObj, runtime, step);
        }
        const html = captureArtifactHtml(documentObj, runtime, definition.capture);
        if (!html) {
          throw new Error(`No HTML was captured for ${definition.filename}`);
        }
        const artifact = makeArtifactRecord(definition, {
          status: 'captured',
          rawHtml: html,
          captureBytes: html.length,
          clickPath: steps.map((step) => step.label),
        });
        artifacts.push(artifact);
        capturedByFileName.set(definition.filename, artifact);
      } catch (error) {
        artifacts.push(
          makeArtifactRecord(definition, {
            status: 'failed',
            error: describeError(error),
            clickPath: Array.isArray(definition.steps)
              ? definition.steps.map((step) => step.label)
              : [],
          }),
        );
      }
    }

    DUMP_REGISTRY.filter((definition) => definition.aliasOf).forEach((definition) => {
      const sourceArtifact = capturedByFileName.get(definition.aliasOf);
      if (!sourceArtifact || sourceArtifact.status !== 'captured') {
        artifacts.push(
          makeArtifactRecord(definition, {
            status: 'failed',
            error: `Alias source ${definition.aliasOf} was not captured`,
            aliasOf: definition.aliasOf,
            clickPath: [],
          }),
        );
        return;
      }
      artifacts.push(
        makeArtifactRecord(definition, {
          status: 'alias',
          aliasOf: definition.aliasOf,
          rawHtml: sourceArtifact.rawHtml,
          captureBytes: sourceArtifact.captureBytes,
          clickPath: sourceArtifact.clickPath,
        }),
      );
    });

    DEFERRED_ARTIFACTS.forEach((artifact) => {
      artifacts.push({
        ...artifact,
        clickPath: [],
      });
    });

    await closeOpenMenus(documentObj, windowObj);

    const completedAt = new Date().toISOString();
    const failedArtifacts = artifacts.filter((artifact) => artifact.status === 'failed');
    const capturedArtifacts = artifacts.filter(
      (artifact) => artifact.status === 'captured' || artifact.status === 'alias',
    );

    return {
      ok: failedArtifacts.length === 0,
      runKind: 'devscrapewide',
      fixtureUrl: DEV_SCRAPE_WIDE_FIXTURE_URL,
      pageInfo,
      startedAt,
      completedAt,
      artifacts,
      capturedCount: capturedArtifacts.length,
      failedCount: failedArtifacts.length,
      deferredCount: DEFERRED_ARTIFACTS.length,
    };
  }

  async function persistWideScrapeRun({ windowObj, rootHandle, scrapeResult }) {
    if (!scrapeResult || !Array.isArray(scrapeResult.artifacts)) {
      throw new Error('Scrape result is missing artifacts');
    }
    const runDirectory = await getUniqueRunDirectoryHandle(rootHandle, buildRunFolderName());
    const writtenFiles = [];

    for (const artifact of scrapeResult.artifacts) {
      if (artifact.status !== 'captured' && artifact.status !== 'alias') continue;
      const normalized = normalizeHtmlForDump(windowObj, artifact.rawHtml);
      await writeTextFile(runDirectory, artifact.filename, normalized);
      writtenFiles.push(artifact.filename);
    }

    const manifest = {
      schemaVersion: 1,
      runKind: 'devscrapewide',
      folderName: runDirectory.name,
      fixtureUrl: scrapeResult.fixtureUrl || DEV_SCRAPE_WIDE_FIXTURE_URL,
      pageInfo: scrapeResult.pageInfo || null,
      startedAt: scrapeResult.startedAt || new Date().toISOString(),
      completedAt: scrapeResult.completedAt || new Date().toISOString(),
      writtenFiles,
      deferredFiles: DEFERRED_ARTIFACTS.map((artifact) => artifact.filename),
      artifacts: scrapeResult.artifacts.map((artifact) => {
        const artifactForManifest = { ...artifact };
        delete artifactForManifest.rawHtml;
        return artifactForManifest;
      }),
    };
    await writeTextFile(runDirectory, RUN_MANIFEST_NAME, `${JSON.stringify(manifest, null, 2)}\n`);
    await storeLastRunAfterPersist(runDirectory.name, manifest.completedAt);

    return {
      folderName: runDirectory.name,
      manifest,
      writtenFiles,
      capturedCount: manifest.artifacts.filter(
        (artifact) => artifact.status === 'captured' || artifact.status === 'alias',
      ).length,
      failedCount: manifest.artifacts.filter((artifact) => artifact.status === 'failed').length,
      deferredCount: manifest.deferredFiles.length,
    };
  }

  async function loadRunFromDirectory(directoryHandle) {
    const manifestText = await readTextFile(directoryHandle, RUN_MANIFEST_NAME);
    const manifest = JSON.parse(manifestText);
    const textEntries = (await listDirectoryEntries(directoryHandle)).filter(
      (entry) => entry.handle?.kind === 'file' && entry.name.toLowerCase().endsWith('.txt'),
    );
    const files = {};
    for (const entry of textEntries) {
      files[entry.name] = await readTextFile(directoryHandle, entry.name);
    }
    return { manifest, files };
  }

  async function runWideScrapeCheck({ rootHandle }) {
    const latestRun = await getPreferredRunDirectoryHandle(rootHandle);
    if (!latestRun) {
      throw new Error('No DevScrapeWide capture folders were found');
    }

    const { manifest, files } = await loadRunFromDirectory(latestRun.handle);

    const missingArtifacts = manifest.artifacts
      .filter((artifact) => artifact.status === 'failed')
      .map((artifact) => ({
        filename: artifact.filename,
        reason: artifact.error || 'Capture failed',
      }));

    const missingExpectedFiles = CHECK_RULES.flatMap((rule) =>
      rule.expectedFiles
        .filter((fileName) => !Object.hasOwn(files, fileName))
        .map((fileName) => ({ identifier: rule.identifier, filename: fileName })),
    );

    const rows = CHECK_RULES.map((rule) => {
      const matchingFiles = Object.entries(files)
        .filter(([, text]) =>
          rule.searchNeedles.some((needle) => String(text || '').includes(needle)),
        )
        .map(([fileName]) => fileName)
        .sort();
      const sourcePresent = BUILD_SOURCE_PRESENCE_BY_IDENTIFIER[rule.identifier] !== false;
      return {
        actionId: rule.actionId,
        identifier: rule.identifier,
        files: matchingFiles,
        status: sourcePresent && matchingFiles.length > 0 ? 'pass' : 'fail',
      };
    });

    const summary = {
      total: rows.length,
      passed: rows.filter((row) => row.status === 'pass').length,
      failed: rows.filter((row) => row.status === 'fail').length,
    };

    const report = {
      schemaVersion: 1,
      generatedAt: new Date().toISOString(),
      fixtureUrl: DEV_SCRAPE_WIDE_FIXTURE_URL,
      folderName: latestRun.name,
      runManifest: manifest,
      rows,
      missingArtifacts,
      missingExpectedFiles,
      summary,
    };

    await chrome.storage.local.set({ [DEV_SCRAPE_WIDE_LAST_REPORT_KEY]: report });
    return report;
  }

  function getReportPageUrl() {
    return chrome.runtime.getURL(DEV_SCRAPE_WIDE_REPORT_PATH);
  }

  function summarizeScrapeWriteResult(writeResult) {
    const parts = [`Saved ${writeResult.capturedCount} dumps to ${writeResult.folderName}.`];
    if (writeResult.failedCount) {
      parts.push(
        `${writeResult.failedCount} dump(s) failed; check run-manifest.json before trusting the scrape.`,
      );
    }
    if (writeResult.deferredCount) {
      parts.push(`${writeResult.deferredCount} dump remains deferred.`);
    }
    return parts.join(' ');
  }

  function summarizeCheckResult(report) {
    const parts = [
      `Checked ${report.summary.total} identifiers in ${report.folderName}.`,
      `${report.summary.passed} passed, ${report.summary.failed} failed.`,
    ];
    if (report.missingArtifacts.length) {
      parts.push(`${report.missingArtifacts.length} dump(s) were missing or failed to capture.`);
    }
    return parts.join(' ');
  }


  return {
    DEV_SCRAPE_WIDE_FIXTURE_URL,
    DEV_SCRAPE_WIDE_LAST_REPORT_KEY,
    DEV_SCRAPE_WIDE_LAST_FOLDER_KEY,
    DEV_SCRAPE_WIDE_CAPTURE_ROOT_REQUIRED_ERROR,
    clearStoredCaptureRootHandle,
    ensureCaptureRootHandle,
    configureCaptureRootHandle,
    isCaptureRootRequiredError,
    getWideScrapePageInfo,
    runWideScrapeInPage,
    persistWideScrapeRun,
    runWideScrapeCheck,
    summarizeScrapeWriteResult,
    summarizeCheckResult,
    isAbortError,
  };
})();

  const BUTTON_MIN_OPACITY = '0.08';
  const BUTTON_SIZE_PX = '24px';
  const BUTTON_RIGHT_PX = '16px';
  const BUTTON_FADE_DELAY_MS = 2200;
  const STATUS_BUBBLE_ID = 'tm-devscrape-wide-status';
  const BUTTON_SPECS = Object.freeze([
    {
      id: 'tm-devscrape-set-path',
      bottom: '80px',
      tooltip: 'Set Path',
      iconHtml:
        '<svg viewBox="0 0 24 24" aria-hidden="true" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round;pointer-events:none;"><path d="M3.5 7.5h5l2 2h10"/><path d="M4.5 6h4.3l1.8 1.8h8.9A1.5 1.5 0 0 1 21 9.3v8.2A1.5 1.5 0 0 1 19.5 19h-15A1.5 1.5 0 0 1 3 17.5v-10A1.5 1.5 0 0 1 4.5 6z"/></svg>',
    },
    {
      id: 'tm-devscrape-run-wide',
      bottom: '48px',
      tooltip: 'DevScrapeWide',
      iconHtml:
        '<svg viewBox="0 0 24 24" aria-hidden="true" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round;pointer-events:none;"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 5 5"/><path d="M10.5 8v5"/><path d="M8 10.5h5"/></svg>',
    },
    {
      id: 'tm-devscrape-check-wide',
      bottom: '16px',
      tooltip: 'Check-Scrape',
      iconHtml:
        '<svg viewBox="0 0 24 24" aria-hidden="true" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round;pointer-events:none;"><path d="M9 12.5 11 14.5 15.5 9.5"/><path d="M14 4h5a1.5 1.5 0 0 1 1.5 1.5v13A1.5 1.5 0 0 1 19 20H5a1.5 1.5 0 0 1-1.5-1.5v-13A1.5 1.5 0 0 1 5 4h5"/><path d="M8.5 4.5h5"/></svg>',
    },
  ]);

  const sleepAsync = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const buttonFadeTimers = new WeakMap();
  let statusFadeTimer = 0;
  let controlsMounted = false;

  const escapeHtml = (value) =>
    String(value ?? '')
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');

  const logStatus = (level, message, error = null) => {
    const method = typeof console?.[level] === 'function' ? console[level] : console.log;
    if (error) {
      method('[TM DevScrapeWide] ' + message, error);
      return;
    }
    method('[TM DevScrapeWide] ' + message);
  };

  const ensureStatusBubble = () => {
    let bubble = document.getElementById(STATUS_BUBBLE_ID);
    if (bubble) return bubble;
    bubble = document.createElement('div');
    bubble.id = STATUS_BUBBLE_ID;
    bubble.style.cssText = [
      'position: fixed',
      'right: 48px',
      'bottom: 16px',
      'max-width: 320px',
      'padding: 4px 8px',
      'border-radius: 999px',
      'background: rgba(17,24,39,.92)',
      'color: #f9fafb',
      'font: 11px/1.2 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      'box-shadow: 0 8px 20px rgba(0,0,0,.28)',
      'pointer-events: none',
      'opacity: 0',
      'transform: translateY(4px)',
      'transition: opacity .2s ease, transform .2s ease',
      'z-index: 2147483646',
      'white-space: nowrap',
      'overflow: hidden',
      'text-overflow: ellipsis',
    ].join(';');
    (document.body || document.documentElement).appendChild(bubble);
    return bubble;
  };

  const setStatus = (message, tone = 'neutral') => {
    const bubble = ensureStatusBubble();
    bubble.textContent = message || '';
    bubble.style.color =
      tone === 'error'
        ? '#fecaca'
        : tone === 'warn'
          ? '#fde68a'
          : tone === 'ok'
            ? '#bbf7d0'
            : '#f9fafb';
    bubble.style.opacity = message ? '1' : '0';
    bubble.style.transform = message ? 'translateY(0)' : 'translateY(4px)';
    window.clearTimeout(statusFadeTimer);
    if (!message) return;
    statusFadeTimer = window.setTimeout(() => {
      bubble.style.opacity = '0.08';
      bubble.style.transform = 'translateY(0)';
    }, 3600);
  };

  const setButtonOpacity = (button, value) => {
    button.style.opacity = String(value);
  };

  const scheduleButtonFade = (button) => {
    window.clearTimeout(buttonFadeTimers.get(button));
    const timer = window.setTimeout(() => {
      if (!button.matches(':hover') && !button.disabled) {
        setButtonOpacity(button, BUTTON_MIN_OPACITY);
      }
    }, BUTTON_FADE_DELAY_MS);
    buttonFadeTimers.set(button, timer);
  };

  const addTooltip = (button, text) => {
    const tooltip = document.createElement('div');
    tooltip.textContent = text;
    tooltip.style.cssText = [
      'position: absolute',
      'bottom: 50%',
      'right: 100%',
      'transform: translateX(-10px) translateY(50%)',
      'margin-right: 10px',
      'background: rgba(17,24,39,.96)',
      'color: #fff',
      'border-radius: 5px',
      'padding: 4px 8px',
      'font: 12px/1.2 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      'white-space: nowrap',
      'visibility: hidden',
      'opacity: 0',
      'transition: opacity .2s ease',
      'pointer-events: none',
      'box-shadow: 0 8px 20px rgba(0,0,0,.28)',
    ].join(';');
    button.appendChild(tooltip);
    return tooltip;
  };

  const createButton = (id, iconHTML, bottomPx, tooltipText, clickHandler) => {
    let button = document.getElementById(id);
    if (button instanceof HTMLButtonElement) return button;

    button = document.createElement('button');
    button.id = id;
    button.type = 'button';
    button.setAttribute('aria-label', tooltipText);
    button.style.cssText = [
      'position: fixed',
      'width: ' + BUTTON_SIZE_PX,
      'height: ' + BUTTON_SIZE_PX,
      'padding: 0',
      'bottom: ' + bottomPx,
      'right: ' + BUTTON_RIGHT_PX,
      'border: none',
      'border-radius: 4px',
      'z-index: 2147483646',
      'display: flex',
      'align-items: center',
      'justify-content: center',
      'background: rgba(17,24,39,.92)',
      'box-shadow: 0 0 0 1px rgba(255,255,255,.12), 0 8px 20px rgba(0,0,0,.28)',
      'color: #f9fafb',
      'cursor: pointer',
      'opacity: 1',
      'transition: opacity .3s ease',
      'overflow: visible',
    ].join(';');
    button.innerHTML = iconHTML;

    const tooltip = addTooltip(button, tooltipText);
    button.addEventListener('mouseenter', () => {
      setButtonOpacity(button, '1');
      tooltip.style.visibility = 'visible';
      tooltip.style.opacity = '1';
    });
    button.addEventListener('mouseleave', () => {
      tooltip.style.visibility = 'hidden';
      tooltip.style.opacity = '0';
      if (!button.disabled) {
        setButtonOpacity(button, BUTTON_MIN_OPACITY);
      }
    });
    button.addEventListener('click', clickHandler);

    (document.body || document.documentElement).appendChild(button);
    scheduleButtonFade(button);
    return button;
  };

  const getButtons = () =>
    BUTTON_SPECS.map((spec) => document.getElementById(spec.id)).filter(
      (button) => button instanceof HTMLButtonElement,
    );

  const setBusy = (value) => {
    getButtons().forEach((button) => {
      button.disabled = !!value;
      button.setAttribute('aria-busy', value ? 'true' : 'false');
      button.style.cursor = value ? 'progress' : 'pointer';
      if (value) {
        setButtonOpacity(button, '1');
      } else {
        scheduleButtonFade(button);
      }
    });
  };

  const ensureRootHandle = async () => {
    try {
      return await DevScrapeWide.ensureCaptureRootHandle(window, { interactive: false });
    } catch (error) {
      if (DevScrapeWide.isAbortError(error)) throw error;
      if (!DevScrapeWide.isCaptureRootRequiredError(error)) throw error;
      setStatus('Choose the inspector-captures folder...', 'warn');
      return DevScrapeWide.configureCaptureRootHandle(window);
    }
  };

  const renderReportHtml = (report) => {
    const rows = Array.isArray(report?.rows) ? report.rows : [];
    const missingArtifacts = Array.isArray(report?.missingArtifacts) ? report.missingArtifacts : [];
    const missingExpectedFiles = Array.isArray(report?.missingExpectedFiles)
      ? report.missingExpectedFiles
      : [];
    return [
      '<!doctype html>',
      '<html><head><meta charset="utf-8"><title>DevScrapeWide Report</title>',
      '<style>',
      'body{font:14px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:24px;color:#111827;background:#f8fafc;}',
      'h1{font-size:20px;margin:0 0 12px;}',
      'p{margin:0 0 10px;}',
      'table{border-collapse:collapse;width:100%;background:#fff;}',
      'th,td{border:1px solid #d1d5db;padding:8px 10px;text-align:left;vertical-align:top;}',
      'th{background:#e5e7eb;font-weight:600;}',
      '.ok{color:#166534;font-weight:700;}',
      '.fail{color:#991b1b;font-weight:700;}',
      '.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;}',
      '.section{margin-top:22px;}',
      'ul{margin:8px 0 0 20px;padding:0;}',
      '</style></head><body>',
      '<h1>DevScrapeWide Report</h1>',
      '<p><strong>Fixture:</strong> <span class="mono">' + escapeHtml(report?.fixtureUrl || '') + '</span></p>',
      '<p><strong>Folder:</strong> <span class="mono">' + escapeHtml(report?.folderName || '') + '</span></p>',
      '<p><strong>Summary:</strong> ' + escapeHtml(
        (report?.summary?.passed ?? 0) + ' passed, ' + (report?.summary?.failed ?? 0) + ' failed, ' + (report?.summary?.total ?? 0) + ' total.',
      ) + '</p>',
      '<table><thead><tr><th>Canonical Identifier</th><th>Dump Files</th><th>Status</th></tr></thead><tbody>',
      rows
        .map((row) => {
          const ok = row.status === 'pass';
          return [
            '<tr>',
            '<td class="mono">' + escapeHtml(row.identifier) + '</td>',
            '<td class="mono">' + escapeHtml((row.files || []).join(', ') || '(none)') + '</td>',
            '<td class="' + (ok ? 'ok' : 'fail') + '">' + (ok ? '✓' : 'X likely needs repair because the page changed') + '</td>',
            '</tr>',
          ].join('');
        })
        .join(''),
      '</tbody></table>',
      '<div class="section"><strong>Missing or Failed Dumps</strong>',
      missingArtifacts.length
        ? '<ul>' +
          missingArtifacts
            .map(
              (item) =>
                '<li><span class="mono">' +
                escapeHtml(item.filename) +
                '</span> — ' +
                escapeHtml(item.reason || 'Capture failed') +
                '</li>',
            )
            .join('') +
          '</ul>'
        : '<p>None.</p>',
      '</div>',
      '<div class="section"><strong>Missing Expected Files</strong>',
      missingExpectedFiles.length
        ? '<ul>' +
          missingExpectedFiles
            .map(
              (item) =>
                '<li><span class="mono">' +
                escapeHtml(item.identifier) +
                '</span> expected <span class="mono">' +
                escapeHtml(item.filename) +
                '</span></li>',
            )
            .join('') +
          '</ul>'
        : '<p>None.</p>',
      '</div>',
      '</body></html>',
    ].join('');
  };

  const openReportWindow = (report) => {
    const win = window.open('', '_blank', 'noopener');
    if (!win) return;
    win.document.open();
    win.document.write(renderReportHtml(report));
    win.document.close();
  };

  const mountControls = () => {
    if (controlsMounted) return;
    controlsMounted = true;

    const runWithBusyState = async (task) => {
      if (getButtons().some((button) => button.disabled)) return;
      try {
        setBusy(true);
        await task();
      } catch (error) {
        if (!DevScrapeWide.isAbortError(error)) {
          const message = error?.message || 'Unknown error';
          setStatus(message, 'error');
          logStatus('error', message, error);
        }
      } finally {
        setBusy(false);
      }
    };

    createButton(
      BUTTON_SPECS[0].id,
      BUTTON_SPECS[0].iconHtml,
      BUTTON_SPECS[0].bottom,
      BUTTON_SPECS[0].tooltip,
      () =>
        runWithBusyState(async () => {
          const rootHandle = await DevScrapeWide.configureCaptureRootHandle(window);
          const message =
            'Set Path configured for ' + (rootHandle?.name || 'inspector-captures') + '.';
          setStatus(message, 'ok');
          logStatus('info', message);
        }),
    );

    createButton(
      BUTTON_SPECS[1].id,
      BUTTON_SPECS[1].iconHtml,
      BUTTON_SPECS[1].bottom,
      BUTTON_SPECS[1].tooltip,
      () =>
        runWithBusyState(async () => {
          setStatus('Running wide scrape...', 'neutral');
          const scrapeResult = await DevScrapeWide.runWideScrapeInPage({
            windowObj: window,
            documentObj: document,
          });
          if (!scrapeResult || !Array.isArray(scrapeResult.artifacts)) {
            throw new Error(scrapeResult?.error || 'The ChatGPT page did not complete the scrape');
          }
          const rootHandle = await ensureRootHandle();
          const writeResult = await DevScrapeWide.persistWideScrapeRun({
            windowObj: window,
            rootHandle,
            scrapeResult,
          });
          const summary = DevScrapeWide.summarizeScrapeWriteResult(writeResult);
          const tone = scrapeResult.ok === false ? 'warn' : 'ok';
          setStatus(summary, tone);
          logStatus(tone === 'warn' ? 'warn' : 'info', summary);
        }),
    );

    createButton(
      BUTTON_SPECS[2].id,
      BUTTON_SPECS[2].iconHtml,
      BUTTON_SPECS[2].bottom,
      BUTTON_SPECS[2].tooltip,
      () =>
        runWithBusyState(async () => {
          setStatus('Checking latest scrape...', 'neutral');
          const rootHandle = await ensureRootHandle();
          const report = await DevScrapeWide.runWideScrapeCheck({ rootHandle });
          openReportWindow(report);
          const summary = DevScrapeWide.summarizeCheckResult(report);
          setStatus(summary, report.summary.failed ? 'warn' : 'ok');
          logStatus(report.summary.failed ? 'warn' : 'info', summary);
        }),
    );

    setStatus('Dev scrape ready', 'neutral');
  };

  const start = () => {
    if (document.body) {
      mountControls();
      return;
    }
    setTimeout(start, 50);
  };

  start();
})();
